name: Terraform Lint

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tflint
      uses: terraform-linters/setup-tflint@v1

    - name: Initialize TFLint
      run: tflint --init
      working-directory: terraform

    - name: Run tflint
      run:  tflint --chdir terraform/
